### ISSUE TITLE
[FEAT] Russian localization

### ISSUE THREAD

**Issue by leestarb** [belelaritra/Neumorphic_Calculator#10]
Currently there's no localization for russian users.

I would be glad to add it. However not sure how to do that.

**Comment by danger-ahead** [comment]
Hi @leestarb, I've added the arb file for Russian under `{PROJECT_ROOT}/lib/localization/app_ru.arb`. Could you add the translations there? (For reference have a look at the `{PROJECT_ROOT}/lib/localization/app_en.arb`, the english localization)

Please have a look at the file and let me know if you understand the structure. Thanks!

**Comment by leestarb** [comment]
You missed the translations for `Settings` menu title and `Nothing to show` in history!

**Comment by danger-ahead** [comment]
> You missed the translations for `Settings` menu title and `Nothing to show` in history!

Fixed. Have a look. Thanks!
