### ISSUE TITLE
Newest version not available for download in F-Droid

### ISSUE THREAD

**Issue by ritzd** [belelaritra/Neumorphic_Calculator#5]
Hi.
The newest version (v1.1.0) isn't available for download in F-Droid. It's only available in GitHub releases as of now.

By the way, I loved the Calculator UI.

**Comment by danger-ahead** [comment]
@ritzd Thanks for opening this issue. Please refer to [this](https://gitlab.com/fdroid/fdroiddata/-/issues/2586). This is a bug on F-Droid's part. Hope it gets fixed soon.

**Comment by danger-ahead** [comment]
@ritzd the issue has been fixed. Closing this. Let me know if you need help with anything else.
