### ISSUE TITLE
Add a translation [POLISH]

### ISSUE THREAD

**Issue by Valdnet** [belelaritra/Neumorphic_Calculator#8]
I propose to adapt the application to the multilingual version. After the application is released on F-Droid, there will be users who would like the application to be in their native language.

**Comment by danger-ahead** [comment]
@Valdnet Thanks for the proposition. But the current maintainers are only well versed in English. Let me know if you'd like to work on this issue. You could add the language you speak or are well accustomed to.

Thanks!

**Comment by Valdnet** [comment]
> You could add the language you speak or are well accustomed to.

First you need to adapt the code and extracting the text strings into separate files. If your application is developed in Flutter, the best solution is an .arb file.
Then I will gladly translate it into Polish 😉.

> But the current maintainers are only well versed in English.

You don't need to know any other languages. The translation will be done by translators who know English and will translate into their native language and more. The best solution would be to add the project to Weblate or POEditor.

**Comment by danger-ahead** [comment]
Thanks @Valdnet. Will let you know once we do the required changes.

**Comment by danger-ahead** [comment]
Hi @Valdnet, I've added the arb file for Polish under `{PROJECT_ROOT}/lib/localization/app_pl.arb`. Could please add the translations and issue a PR?

Thanks!
Also I'm assigning you on this.

**Comment by Valdnet** [comment]
@danger-ahead Please add a commit with the following translation:

```
{
	"title": "Kalkulator",
	"about": "O aplikacji",
	"hapticFeedback": "Dotykowa informacja zwrotna",
	"theme": "Wygląd",
	"advanced": "Zaawansowany",
	"history": "Historia",
	"historyEmpty": "Nie ma nic do pokazania :(",
	"settings": "Ustawienia"
}
```

Thanks 😉.

**Comment by danger-ahead** [comment]
Thanks @Valdnet. Closing this issue now.

**Comment by Valdnet** [comment]
@danger-ahead Please make the following change to the translation:

`"theme": "Wygląd",` -> `"theme": "Motyw",`

Thanks 😉.
